// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ai_providers.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

// ---------------------------------------------------------------------------
// ai_providers
// ---------------------------------------------------------------------------

const createAiProvider = `-- name: CreateAiProvider :one
INSERT INTO ai_providers (tenant_id, name, provider, base_url, api_key_env, enabled)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, name, provider, base_url, api_key_env, enabled, created_at, updated_at
`

type CreateAiProviderParams struct {
	TenantID  uuid.UUID `db:"tenant_id" json:"tenant_id"`
	Name      string    `db:"name" json:"name"`
	Provider  string    `db:"provider" json:"provider"`
	BaseURL   *string   `db:"base_url" json:"base_url"`
	ApiKeyEnv *string   `db:"api_key_env" json:"api_key_env"`
	Enabled   bool      `db:"enabled" json:"enabled"`
}

func (q *Queries) CreateAiProvider(ctx context.Context, arg CreateAiProviderParams) (AiProvider, error) {
	row := q.db.QueryRow(ctx, createAiProvider,
		arg.TenantID, arg.Name, arg.Provider, arg.BaseURL, arg.ApiKeyEnv, arg.Enabled,
	)
	var i AiProvider
	err := row.Scan(
		&i.ID, &i.TenantID, &i.Name, &i.Provider,
		&i.BaseURL, &i.ApiKeyEnv, &i.Enabled,
		&i.CreatedAt, &i.UpdatedAt,
	)
	return i, err
}

const getAiProvider = `-- name: GetAiProvider :one
SELECT id, tenant_id, name, provider, base_url, api_key_env, enabled, created_at, updated_at
FROM ai_providers
WHERE id = $1 AND tenant_id = $2
`

type GetAiProviderParams struct {
	ID       uuid.UUID `db:"id" json:"id"`
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
}

func (q *Queries) GetAiProvider(ctx context.Context, arg GetAiProviderParams) (AiProvider, error) {
	row := q.db.QueryRow(ctx, getAiProvider, arg.ID, arg.TenantID)
	var i AiProvider
	err := row.Scan(
		&i.ID, &i.TenantID, &i.Name, &i.Provider,
		&i.BaseURL, &i.ApiKeyEnv, &i.Enabled,
		&i.CreatedAt, &i.UpdatedAt,
	)
	return i, err
}

const listAiProvidersByTenant = `-- name: ListAiProvidersByTenant :many
SELECT id, tenant_id, name, provider, base_url, api_key_env, enabled, created_at, updated_at
FROM ai_providers
WHERE tenant_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListAiProvidersByTenantParams struct {
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
	Limit    int32     `db:"limit" json:"limit"`
	Offset   int32     `db:"offset" json:"offset"`
}

func (q *Queries) ListAiProvidersByTenant(ctx context.Context, arg ListAiProvidersByTenantParams) ([]AiProvider, error) {
	rows, err := q.db.Query(ctx, listAiProvidersByTenant, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AiProvider
	for rows.Next() {
		var i AiProvider
		if err := rows.Scan(
			&i.ID, &i.TenantID, &i.Name, &i.Provider,
			&i.BaseURL, &i.ApiKeyEnv, &i.Enabled,
			&i.CreatedAt, &i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAiProvider = `-- name: UpdateAiProvider :one
UPDATE ai_providers
SET name = $3, provider = $4, base_url = $5, api_key_env = $6, enabled = $7, updated_at = now()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, name, provider, base_url, api_key_env, enabled, created_at, updated_at
`

type UpdateAiProviderParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	TenantID  uuid.UUID `db:"tenant_id" json:"tenant_id"`
	Name      string    `db:"name" json:"name"`
	Provider  string    `db:"provider" json:"provider"`
	BaseURL   *string   `db:"base_url" json:"base_url"`
	ApiKeyEnv *string   `db:"api_key_env" json:"api_key_env"`
	Enabled   bool      `db:"enabled" json:"enabled"`
}

func (q *Queries) UpdateAiProvider(ctx context.Context, arg UpdateAiProviderParams) (AiProvider, error) {
	row := q.db.QueryRow(ctx, updateAiProvider,
		arg.ID, arg.TenantID, arg.Name, arg.Provider,
		arg.BaseURL, arg.ApiKeyEnv, arg.Enabled,
	)
	var i AiProvider
	err := row.Scan(
		&i.ID, &i.TenantID, &i.Name, &i.Provider,
		&i.BaseURL, &i.ApiKeyEnv, &i.Enabled,
		&i.CreatedAt, &i.UpdatedAt,
	)
	return i, err
}

const deleteAiProvider = `-- name: DeleteAiProvider :exec
DELETE FROM ai_providers
WHERE id = $1 AND tenant_id = $2
`

type DeleteAiProviderParams struct {
	ID       uuid.UUID `db:"id" json:"id"`
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
}

func (q *Queries) DeleteAiProvider(ctx context.Context, arg DeleteAiProviderParams) error {
	_, err := q.db.Exec(ctx, deleteAiProvider, arg.ID, arg.TenantID)
	return err
}

// ---------------------------------------------------------------------------
// ai_model_policies
// ---------------------------------------------------------------------------

const createAiModelPolicy = `-- name: CreateAiModelPolicy :one
INSERT INTO ai_model_policies (tenant_id, provider_id, model, max_tokens_per_request, budget_usd_per_day, fallback_model, enabled)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, tenant_id, provider_id, model, max_tokens_per_request, budget_usd_per_day::text, fallback_model, enabled, created_at, updated_at
`

type CreateAiModelPolicyParams struct {
	TenantID            uuid.UUID `db:"tenant_id" json:"tenant_id"`
	ProviderID          uuid.UUID `db:"provider_id" json:"provider_id"`
	Model               string    `db:"model" json:"model"`
	MaxTokensPerRequest int32     `db:"max_tokens_per_request" json:"max_tokens_per_request"`
	BudgetUsdPerDay     *string   `db:"budget_usd_per_day" json:"budget_usd_per_day"`
	FallbackModel       *string   `db:"fallback_model" json:"fallback_model"`
	Enabled             bool      `db:"enabled" json:"enabled"`
}

func (q *Queries) CreateAiModelPolicy(ctx context.Context, arg CreateAiModelPolicyParams) (AiModelPolicy, error) {
	row := q.db.QueryRow(ctx, createAiModelPolicy,
		arg.TenantID, arg.ProviderID, arg.Model,
		arg.MaxTokensPerRequest, arg.BudgetUsdPerDay,
		arg.FallbackModel, arg.Enabled,
	)
	var i AiModelPolicy
	err := row.Scan(
		&i.ID, &i.TenantID, &i.ProviderID, &i.Model,
		&i.MaxTokensPerRequest, &i.BudgetUsdPerDay,
		&i.FallbackModel, &i.Enabled,
		&i.CreatedAt, &i.UpdatedAt,
	)
	return i, err
}

const getAiModelPolicy = `-- name: GetAiModelPolicy :one
SELECT id, tenant_id, provider_id, model, max_tokens_per_request, budget_usd_per_day::text, fallback_model, enabled, created_at, updated_at
FROM ai_model_policies
WHERE id = $1 AND tenant_id = $2
`

type GetAiModelPolicyParams struct {
	ID       uuid.UUID `db:"id" json:"id"`
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
}

func (q *Queries) GetAiModelPolicy(ctx context.Context, arg GetAiModelPolicyParams) (AiModelPolicy, error) {
	row := q.db.QueryRow(ctx, getAiModelPolicy, arg.ID, arg.TenantID)
	var i AiModelPolicy
	err := row.Scan(
		&i.ID, &i.TenantID, &i.ProviderID, &i.Model,
		&i.MaxTokensPerRequest, &i.BudgetUsdPerDay,
		&i.FallbackModel, &i.Enabled,
		&i.CreatedAt, &i.UpdatedAt,
	)
	return i, err
}

const listAiModelPoliciesByProvider = `-- name: ListAiModelPoliciesByProvider :many
SELECT id, tenant_id, provider_id, model, max_tokens_per_request, budget_usd_per_day::text, fallback_model, enabled, created_at, updated_at
FROM ai_model_policies
WHERE provider_id = $1 AND tenant_id = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListAiModelPoliciesByProviderParams struct {
	ProviderID uuid.UUID `db:"provider_id" json:"provider_id"`
	TenantID   uuid.UUID `db:"tenant_id" json:"tenant_id"`
	Limit      int32     `db:"limit" json:"limit"`
	Offset     int32     `db:"offset" json:"offset"`
}

func (q *Queries) ListAiModelPoliciesByProvider(ctx context.Context, arg ListAiModelPoliciesByProviderParams) ([]AiModelPolicy, error) {
	rows, err := q.db.Query(ctx, listAiModelPoliciesByProvider,
		arg.ProviderID, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AiModelPolicy
	for rows.Next() {
		var i AiModelPolicy
		if err := rows.Scan(
			&i.ID, &i.TenantID, &i.ProviderID, &i.Model,
			&i.MaxTokensPerRequest, &i.BudgetUsdPerDay,
			&i.FallbackModel, &i.Enabled,
			&i.CreatedAt, &i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAiModelPolicy = `-- name: UpdateAiModelPolicy :one
UPDATE ai_model_policies
SET model = $3, max_tokens_per_request = $4, budget_usd_per_day = $5, fallback_model = $6, enabled = $7, updated_at = now()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, provider_id, model, max_tokens_per_request, budget_usd_per_day::text, fallback_model, enabled, created_at, updated_at
`

type UpdateAiModelPolicyParams struct {
	ID                  uuid.UUID `db:"id" json:"id"`
	TenantID            uuid.UUID `db:"tenant_id" json:"tenant_id"`
	Model               string    `db:"model" json:"model"`
	MaxTokensPerRequest int32     `db:"max_tokens_per_request" json:"max_tokens_per_request"`
	BudgetUsdPerDay     *string   `db:"budget_usd_per_day" json:"budget_usd_per_day"`
	FallbackModel       *string   `db:"fallback_model" json:"fallback_model"`
	Enabled             bool      `db:"enabled" json:"enabled"`
}

func (q *Queries) UpdateAiModelPolicy(ctx context.Context, arg UpdateAiModelPolicyParams) (AiModelPolicy, error) {
	row := q.db.QueryRow(ctx, updateAiModelPolicy,
		arg.ID, arg.TenantID, arg.Model,
		arg.MaxTokensPerRequest, arg.BudgetUsdPerDay,
		arg.FallbackModel, arg.Enabled,
	)
	var i AiModelPolicy
	err := row.Scan(
		&i.ID, &i.TenantID, &i.ProviderID, &i.Model,
		&i.MaxTokensPerRequest, &i.BudgetUsdPerDay,
		&i.FallbackModel, &i.Enabled,
		&i.CreatedAt, &i.UpdatedAt,
	)
	return i, err
}

const deleteAiModelPolicy = `-- name: DeleteAiModelPolicy :exec
DELETE FROM ai_model_policies
WHERE id = $1 AND tenant_id = $2
`

type DeleteAiModelPolicyParams struct {
	ID       uuid.UUID `db:"id" json:"id"`
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
}

func (q *Queries) DeleteAiModelPolicy(ctx context.Context, arg DeleteAiModelPolicyParams) error {
	_, err := q.db.Exec(ctx, deleteAiModelPolicy, arg.ID, arg.TenantID)
	return err
}
