// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: checkpoints.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const createCheckpoint = `-- name: CreateCheckpoint :one
INSERT INTO config_checkpoints (tenant_id, sequence, outbox_last_id, note)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, sequence, outbox_last_id, note, created_at
`

type CreateCheckpointParams struct {
	TenantID     uuid.UUID `db:"tenant_id" json:"tenant_id"`
	Sequence     int64     `db:"sequence" json:"sequence"`
	OutboxLastID *int64    `db:"outbox_last_id" json:"outbox_last_id"`
	Note         *string   `db:"note" json:"note"`
}

func (q *Queries) CreateCheckpoint(ctx context.Context, arg CreateCheckpointParams) (ConfigCheckpoint, error) {
	row := q.db.QueryRow(ctx, createCheckpoint,
		arg.TenantID,
		arg.Sequence,
		arg.OutboxLastID,
		arg.Note,
	)
	var i ConfigCheckpoint
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Sequence,
		&i.OutboxLastID,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCheckpoint = `-- name: DeleteCheckpoint :exec
DELETE FROM config_checkpoints
WHERE id = $1 AND tenant_id = $2
`

type DeleteCheckpointParams struct {
	ID       uuid.UUID `db:"id" json:"id"`
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
}

func (q *Queries) DeleteCheckpoint(ctx context.Context, arg DeleteCheckpointParams) error {
	_, err := q.db.Exec(ctx, deleteCheckpoint, arg.ID, arg.TenantID)
	return err
}

const getCheckpointBySequence = `-- name: GetCheckpointBySequence :one
SELECT id, tenant_id, sequence, outbox_last_id, note, created_at FROM config_checkpoints
WHERE tenant_id = $1 AND sequence = $2
`

type GetCheckpointBySequenceParams struct {
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
	Sequence int64     `db:"sequence" json:"sequence"`
}

func (q *Queries) GetCheckpointBySequence(ctx context.Context, arg GetCheckpointBySequenceParams) (ConfigCheckpoint, error) {
	row := q.db.QueryRow(ctx, getCheckpointBySequence, arg.TenantID, arg.Sequence)
	var i ConfigCheckpoint
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Sequence,
		&i.OutboxLastID,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const listCheckpoints = `-- name: ListCheckpoints :many
SELECT id, tenant_id, sequence, outbox_last_id, note, created_at FROM config_checkpoints
WHERE tenant_id = $1
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type ListCheckpointsParams struct {
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
	Off      int32     `db:"off" json:"off"`
	Lim      int32     `db:"lim" json:"lim"`
}

func (q *Queries) ListCheckpoints(ctx context.Context, arg ListCheckpointsParams) ([]ConfigCheckpoint, error) {
	rows, err := q.db.Query(ctx, listCheckpoints, arg.TenantID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConfigCheckpoint
	for rows.Next() {
		var i ConfigCheckpoint
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Sequence,
			&i.OutboxLastID,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
