// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ConfigCheckpoint struct {
	ID           uuid.UUID `db:"id" json:"id"`
	TenantID     uuid.UUID `db:"tenant_id" json:"tenant_id"`
	Sequence     int64     `db:"sequence" json:"sequence"`
	OutboxLastID *int64    `db:"outbox_last_id" json:"outbox_last_id"`
	Note         *string   `db:"note" json:"note"`
	CreatedAt    time.Time `db:"created_at" json:"created_at"`
}

type Consumer struct {
	ID        uuid.UUID `db:"id" json:"id"`
	TenantID  uuid.UUID `db:"tenant_id" json:"tenant_id"`
	Name      string    `db:"name" json:"name"`
	Enabled   bool      `db:"enabled" json:"enabled"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
	UpdatedAt time.Time `db:"updated_at" json:"updated_at"`
}

type EventOutbox struct {
	ID             int64              `db:"id" json:"id"`
	TenantID       uuid.UUID          `db:"tenant_id" json:"tenant_id"`
	KafkaTopic     string             `db:"kafka_topic" json:"kafka_topic"`
	Payload        []byte             `db:"payload" json:"payload"`
	CreatedAt      time.Time          `db:"created_at" json:"created_at"`
	SentAt         pgtype.Timestamptz `db:"sent_at" json:"sent_at"`
	KafkaPartition *int32             `db:"kafka_partition" json:"kafka_partition"`
	KafkaOffset    *int64             `db:"kafka_offset" json:"kafka_offset"`
}

type Policy struct {
	ID        uuid.UUID `db:"id" json:"id"`
	TenantID  uuid.UUID `db:"tenant_id" json:"tenant_id"`
	Name      string    `db:"name" json:"name"`
	Type      string    `db:"type" json:"type"`
	Config    []byte    `db:"config" json:"config"`
	Enabled   bool      `db:"enabled" json:"enabled"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
	UpdatedAt time.Time `db:"updated_at" json:"updated_at"`
}

type Route struct {
	ID         uuid.UUID `db:"id" json:"id"`
	TenantID   uuid.UUID `db:"tenant_id" json:"tenant_id"`
	Method     string    `db:"method" json:"method"`
	PathPrefix string    `db:"path_prefix" json:"path_prefix"`
	Host       string    `db:"host" json:"host"`
	UpstreamID uuid.UUID `db:"upstream_id" json:"upstream_id"`
	Enabled    bool      `db:"enabled" json:"enabled"`
	CreatedAt  time.Time `db:"created_at" json:"created_at"`
	UpdatedAt  time.Time `db:"updated_at" json:"updated_at"`
}

type RoutePolicy struct {
	RouteID  uuid.UUID `db:"route_id" json:"route_id"`
	PolicyID uuid.UUID `db:"policy_id" json:"policy_id"`
	Position int32     `db:"position" json:"position"`
}

type Tenant struct {
	ID        uuid.UUID `db:"id" json:"id"`
	Name      string    `db:"name" json:"name"`
	Slug      string    `db:"slug" json:"slug"`
	Enabled   bool      `db:"enabled" json:"enabled"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
	UpdatedAt time.Time `db:"updated_at" json:"updated_at"`
}

type Upstream struct {
	ID        uuid.UUID `db:"id" json:"id"`
	TenantID  uuid.UUID `db:"tenant_id" json:"tenant_id"`
	Name      string    `db:"name" json:"name"`
	Url       string    `db:"url" json:"url"`
	TimeoutMs int32     `db:"timeout_ms" json:"timeout_ms"`
	Enabled   bool      `db:"enabled" json:"enabled"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
	UpdatedAt time.Time `db:"updated_at" json:"updated_at"`
}

type AiProvider struct {
	ID        uuid.UUID `db:"id" json:"id"`
	TenantID  uuid.UUID `db:"tenant_id" json:"tenant_id"`
	Name      string    `db:"name" json:"name"`
	Provider  string    `db:"provider" json:"provider"`
	BaseURL   *string   `db:"base_url" json:"base_url,omitempty"`
	ApiKeyEnv *string   `db:"api_key_env" json:"api_key_env,omitempty"`
	Enabled   bool      `db:"enabled" json:"enabled"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
	UpdatedAt time.Time `db:"updated_at" json:"updated_at"`
}

type AiModelPolicy struct {
	ID                  uuid.UUID `db:"id" json:"id"`
	TenantID            uuid.UUID `db:"tenant_id" json:"tenant_id"`
	ProviderID          uuid.UUID `db:"provider_id" json:"provider_id"`
	Model               string    `db:"model" json:"model"`
	MaxTokensPerRequest int32     `db:"max_tokens_per_request" json:"max_tokens_per_request"`
	BudgetUsdPerDay     *string   `db:"budget_usd_per_day" json:"budget_usd_per_day,omitempty"`
	FallbackModel       *string   `db:"fallback_model" json:"fallback_model,omitempty"`
	Enabled             bool      `db:"enabled" json:"enabled"`
	CreatedAt           time.Time `db:"created_at" json:"created_at"`
	UpdatedAt           time.Time `db:"updated_at" json:"updated_at"`
}
