// Code generated by sqlc. DO NOT EDIT.

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

// ---------- model (appended to models.go conceptually) ----------

type RateLimitPolicy struct {
	ID          uuid.UUID  `db:"id" json:"id"`
	TenantID    uuid.UUID  `db:"tenant_id" json:"tenant_id"`
	Name        string     `db:"name" json:"name"`
	Scope       string     `db:"scope" json:"scope"`
	Algorithm   string     `db:"algorithm" json:"algorithm"`
	RateLimit   int32      `db:"rate_limit" json:"rate_limit"`
	WindowSecs  int32      `db:"window_secs" json:"window_secs"`
	BurstLimit  *int32     `db:"burst_limit" json:"burst_limit,omitempty"`
	Enabled     bool       `db:"enabled" json:"enabled"`
	CreatedAt   time.Time  `db:"created_at" json:"created_at"`
	UpdatedAt   time.Time  `db:"updated_at" json:"updated_at"`
}

// ---------- queries ----------

const createRateLimitPolicy = `-- name: CreateRateLimitPolicy :one
INSERT INTO rate_limit_policies (tenant_id, name, scope, algorithm, rate_limit, window_secs, burst_limit, enabled)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, tenant_id, name, scope, algorithm, rate_limit, window_secs, burst_limit, enabled, created_at, updated_at`

type CreateRateLimitPolicyParams struct {
	TenantID   uuid.UUID `db:"tenant_id"`
	Name       string    `db:"name"`
	Scope      string    `db:"scope"`
	Algorithm  string    `db:"algorithm"`
	RateLimit  int32     `db:"rate_limit"`
	WindowSecs int32     `db:"window_secs"`
	BurstLimit *int32    `db:"burst_limit"`
	Enabled    bool      `db:"enabled"`
}

func (q *Queries) CreateRateLimitPolicy(ctx context.Context, arg CreateRateLimitPolicyParams) (RateLimitPolicy, error) {
	row := q.db.QueryRow(ctx, createRateLimitPolicy,
		arg.TenantID, arg.Name, arg.Scope, arg.Algorithm,
		arg.RateLimit, arg.WindowSecs, arg.BurstLimit, arg.Enabled,
	)
	var p RateLimitPolicy
	err := row.Scan(
		&p.ID, &p.TenantID, &p.Name, &p.Scope, &p.Algorithm,
		&p.RateLimit, &p.WindowSecs, &p.BurstLimit, &p.Enabled,
		&p.CreatedAt, &p.UpdatedAt,
	)
	return p, err
}

const listRateLimitPolicies = `-- name: ListRateLimitPolicies :many
SELECT id, tenant_id, name, scope, algorithm, rate_limit, window_secs, burst_limit, enabled, created_at, updated_at
FROM rate_limit_policies
WHERE tenant_id = $1
ORDER BY name
LIMIT $2 OFFSET $3`

type ListRateLimitPoliciesParams struct {
	TenantID uuid.UUID `db:"tenant_id"`
	Limit    int32     `db:"limit"`
	Offset   int32     `db:"offset"`
}

func (q *Queries) ListRateLimitPolicies(ctx context.Context, arg ListRateLimitPoliciesParams) ([]RateLimitPolicy, error) {
	rows, err := q.db.Query(ctx, listRateLimitPolicies, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RateLimitPolicy
	for rows.Next() {
		var p RateLimitPolicy
		if err := rows.Scan(
			&p.ID, &p.TenantID, &p.Name, &p.Scope, &p.Algorithm,
			&p.RateLimit, &p.WindowSecs, &p.BurstLimit, &p.Enabled,
			&p.CreatedAt, &p.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, p)
	}
	return items, rows.Err()
}

const getRateLimitPolicy = `-- name: GetRateLimitPolicy :one
SELECT id, tenant_id, name, scope, algorithm, rate_limit, window_secs, burst_limit, enabled, created_at, updated_at
FROM rate_limit_policies
WHERE id = $1 AND tenant_id = $2`

type GetRateLimitPolicyParams struct {
	ID       uuid.UUID `db:"id"`
	TenantID uuid.UUID `db:"tenant_id"`
}

func (q *Queries) GetRateLimitPolicy(ctx context.Context, arg GetRateLimitPolicyParams) (RateLimitPolicy, error) {
	row := q.db.QueryRow(ctx, getRateLimitPolicy, arg.ID, arg.TenantID)
	var p RateLimitPolicy
	err := row.Scan(
		&p.ID, &p.TenantID, &p.Name, &p.Scope, &p.Algorithm,
		&p.RateLimit, &p.WindowSecs, &p.BurstLimit, &p.Enabled,
		&p.CreatedAt, &p.UpdatedAt,
	)
	return p, err
}

const updateRateLimitPolicy = `-- name: UpdateRateLimitPolicy :one
UPDATE rate_limit_policies
SET name = $3, scope = $4, algorithm = $5, rate_limit = $6,
    window_secs = $7, burst_limit = $8, enabled = $9,
    updated_at = NOW()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, name, scope, algorithm, rate_limit, window_secs, burst_limit, enabled, created_at, updated_at`

type UpdateRateLimitPolicyParams struct {
	ID         uuid.UUID `db:"id"`
	TenantID   uuid.UUID `db:"tenant_id"`
	Name       string    `db:"name"`
	Scope      string    `db:"scope"`
	Algorithm  string    `db:"algorithm"`
	RateLimit  int32     `db:"rate_limit"`
	WindowSecs int32     `db:"window_secs"`
	BurstLimit *int32    `db:"burst_limit"`
	Enabled    bool      `db:"enabled"`
}

func (q *Queries) UpdateRateLimitPolicy(ctx context.Context, arg UpdateRateLimitPolicyParams) (RateLimitPolicy, error) {
	row := q.db.QueryRow(ctx, updateRateLimitPolicy,
		arg.ID, arg.TenantID, arg.Name, arg.Scope, arg.Algorithm,
		arg.RateLimit, arg.WindowSecs, arg.BurstLimit, arg.Enabled,
	)
	var p RateLimitPolicy
	err := row.Scan(
		&p.ID, &p.TenantID, &p.Name, &p.Scope, &p.Algorithm,
		&p.RateLimit, &p.WindowSecs, &p.BurstLimit, &p.Enabled,
		&p.CreatedAt, &p.UpdatedAt,
	)
	return p, err
}

const deleteRateLimitPolicy = `-- name: DeleteRateLimitPolicy :exec
DELETE FROM rate_limit_policies WHERE id = $1 AND tenant_id = $2`

type DeleteRateLimitPolicyParams struct {
	ID       uuid.UUID `db:"id"`
	TenantID uuid.UUID `db:"tenant_id"`
}

func (q *Queries) DeleteRateLimitPolicy(ctx context.Context, arg DeleteRateLimitPolicyParams) error {
	_, err := q.db.Exec(ctx, deleteRateLimitPolicy, arg.ID, arg.TenantID)
	return err
}
