// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: regions.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const createRegion = `-- name: CreateRegion :one
INSERT INTO regions (name, kafka_brokers, is_primary, mm2_group_id, enabled)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, kafka_brokers, is_primary, mm2_group_id, enabled, created_at, updated_at
`

type CreateRegionParams struct {
	Name         string  `db:"name" json:"name"`
	KafkaBrokers string  `db:"kafka_brokers" json:"kafka_brokers"`
	IsPrimary    bool    `db:"is_primary" json:"is_primary"`
	Mm2GroupID   *string `db:"mm2_group_id" json:"mm2_group_id"`
	Enabled      bool    `db:"enabled" json:"enabled"`
}

func (q *Queries) CreateRegion(ctx context.Context, arg CreateRegionParams) (Region, error) {
	row := q.db.QueryRow(ctx, createRegion,
		arg.Name, arg.KafkaBrokers, arg.IsPrimary, arg.Mm2GroupID, arg.Enabled,
	)
	var i Region
	err := row.Scan(
		&i.ID, &i.Name, &i.KafkaBrokers, &i.IsPrimary,
		&i.Mm2GroupID, &i.Enabled, &i.CreatedAt, &i.UpdatedAt,
	)
	return i, err
}

const getRegion = `-- name: GetRegion :one
SELECT id, name, kafka_brokers, is_primary, mm2_group_id, enabled, created_at, updated_at
FROM regions WHERE id = $1
`

func (q *Queries) GetRegion(ctx context.Context, id uuid.UUID) (Region, error) {
	row := q.db.QueryRow(ctx, getRegion, id)
	var i Region
	err := row.Scan(
		&i.ID, &i.Name, &i.KafkaBrokers, &i.IsPrimary,
		&i.Mm2GroupID, &i.Enabled, &i.CreatedAt, &i.UpdatedAt,
	)
	return i, err
}

const listRegions = `-- name: ListRegions :many
SELECT id, name, kafka_brokers, is_primary, mm2_group_id, enabled, created_at, updated_at
FROM regions ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListRegionsParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

func (q *Queries) ListRegions(ctx context.Context, arg ListRegionsParams) ([]Region, error) {
	rows, err := q.db.Query(ctx, listRegions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Region
	for rows.Next() {
		var i Region
		if err := rows.Scan(
			&i.ID, &i.Name, &i.KafkaBrokers, &i.IsPrimary,
			&i.Mm2GroupID, &i.Enabled, &i.CreatedAt, &i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRegion = `-- name: UpdateRegion :one
UPDATE regions
SET name = $2, kafka_brokers = $3, is_primary = $4, mm2_group_id = $5, enabled = $6, updated_at = now()
WHERE id = $1
RETURNING id, name, kafka_brokers, is_primary, mm2_group_id, enabled, created_at, updated_at
`

type UpdateRegionParams struct {
	ID           uuid.UUID `db:"id" json:"id"`
	Name         string    `db:"name" json:"name"`
	KafkaBrokers string    `db:"kafka_brokers" json:"kafka_brokers"`
	IsPrimary    bool      `db:"is_primary" json:"is_primary"`
	Mm2GroupID   *string   `db:"mm2_group_id" json:"mm2_group_id"`
	Enabled      bool      `db:"enabled" json:"enabled"`
}

func (q *Queries) UpdateRegion(ctx context.Context, arg UpdateRegionParams) (Region, error) {
	row := q.db.QueryRow(ctx, updateRegion,
		arg.ID, arg.Name, arg.KafkaBrokers, arg.IsPrimary, arg.Mm2GroupID, arg.Enabled,
	)
	var i Region
	err := row.Scan(
		&i.ID, &i.Name, &i.KafkaBrokers, &i.IsPrimary,
		&i.Mm2GroupID, &i.Enabled, &i.CreatedAt, &i.UpdatedAt,
	)
	return i, err
}

const deleteRegion = `-- name: DeleteRegion :exec
DELETE FROM regions WHERE id = $1
`

func (q *Queries) DeleteRegion(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRegion, id)
	return err
}
