// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: routes.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const createRoute = `-- name: CreateRoute :one
INSERT INTO routes (tenant_id, method, path_prefix, host, upstream_id, enabled)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, method, path_prefix, host, upstream_id, enabled, created_at, updated_at
`

type CreateRouteParams struct {
	TenantID   uuid.UUID `db:"tenant_id" json:"tenant_id"`
	Method     string    `db:"method" json:"method"`
	PathPrefix string    `db:"path_prefix" json:"path_prefix"`
	Host       string    `db:"host" json:"host"`
	UpstreamID uuid.UUID `db:"upstream_id" json:"upstream_id"`
	Enabled    bool      `db:"enabled" json:"enabled"`
}

func (q *Queries) CreateRoute(ctx context.Context, arg CreateRouteParams) (Route, error) {
	row := q.db.QueryRow(ctx, createRoute,
		arg.TenantID,
		arg.Method,
		arg.PathPrefix,
		arg.Host,
		arg.UpstreamID,
		arg.Enabled,
	)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Method,
		&i.PathPrefix,
		&i.Host,
		&i.UpstreamID,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRoute = `-- name: DeleteRoute :exec
DELETE FROM routes
WHERE id = $1 AND tenant_id = $2
`

type DeleteRouteParams struct {
	ID       uuid.UUID `db:"id" json:"id"`
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
}

func (q *Queries) DeleteRoute(ctx context.Context, arg DeleteRouteParams) error {
	_, err := q.db.Exec(ctx, deleteRoute, arg.ID, arg.TenantID)
	return err
}

const getRoute = `-- name: GetRoute :one
SELECT id, tenant_id, method, path_prefix, host, upstream_id, enabled, created_at, updated_at FROM routes
WHERE id = $1 AND tenant_id = $2
`

type GetRouteParams struct {
	ID       uuid.UUID `db:"id" json:"id"`
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
}

func (q *Queries) GetRoute(ctx context.Context, arg GetRouteParams) (Route, error) {
	row := q.db.QueryRow(ctx, getRoute, arg.ID, arg.TenantID)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Method,
		&i.PathPrefix,
		&i.Host,
		&i.UpstreamID,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRoutesByTenant = `-- name: ListRoutesByTenant :many
SELECT id, tenant_id, method, path_prefix, host, upstream_id, enabled, created_at, updated_at FROM routes
WHERE tenant_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListRoutesByTenantParams struct {
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
	Limit    int32     `db:"limit" json:"limit"`
	Offset   int32     `db:"offset" json:"offset"`
}

func (q *Queries) ListRoutesByTenant(ctx context.Context, arg ListRoutesByTenantParams) ([]Route, error) {
	rows, err := q.db.Query(ctx, listRoutesByTenant, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Route
	for rows.Next() {
		var i Route
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Method,
			&i.PathPrefix,
			&i.Host,
			&i.UpstreamID,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRoute = `-- name: UpdateRoute :one
UPDATE routes
SET method = $3, path_prefix = $4, host = $5, upstream_id = $6, enabled = $7
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, method, path_prefix, host, upstream_id, enabled, created_at, updated_at
`

type UpdateRouteParams struct {
	ID         uuid.UUID `db:"id" json:"id"`
	TenantID   uuid.UUID `db:"tenant_id" json:"tenant_id"`
	Method     string    `db:"method" json:"method"`
	PathPrefix string    `db:"path_prefix" json:"path_prefix"`
	Host       string    `db:"host" json:"host"`
	UpstreamID uuid.UUID `db:"upstream_id" json:"upstream_id"`
	Enabled    bool      `db:"enabled" json:"enabled"`
}

func (q *Queries) UpdateRoute(ctx context.Context, arg UpdateRouteParams) (Route, error) {
	row := q.db.QueryRow(ctx, updateRoute,
		arg.ID,
		arg.TenantID,
		arg.Method,
		arg.PathPrefix,
		arg.Host,
		arg.UpstreamID,
		arg.Enabled,
	)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Method,
		&i.PathPrefix,
		&i.Host,
		&i.UpstreamID,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
