// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: upstreams.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const createUpstream = `-- name: CreateUpstream :one
INSERT INTO upstreams (tenant_id, name, url, timeout_ms, enabled)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, name, url, timeout_ms, enabled, created_at, updated_at
`

type CreateUpstreamParams struct {
	TenantID  uuid.UUID `db:"tenant_id" json:"tenant_id"`
	Name      string    `db:"name" json:"name"`
	Url       string    `db:"url" json:"url"`
	TimeoutMs int32     `db:"timeout_ms" json:"timeout_ms"`
	Enabled   bool      `db:"enabled" json:"enabled"`
}

func (q *Queries) CreateUpstream(ctx context.Context, arg CreateUpstreamParams) (Upstream, error) {
	row := q.db.QueryRow(ctx, createUpstream,
		arg.TenantID,
		arg.Name,
		arg.Url,
		arg.TimeoutMs,
		arg.Enabled,
	)
	var i Upstream
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Url,
		&i.TimeoutMs,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUpstream = `-- name: DeleteUpstream :exec
DELETE FROM upstreams
WHERE id = $1 AND tenant_id = $2
`

type DeleteUpstreamParams struct {
	ID       uuid.UUID `db:"id" json:"id"`
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
}

func (q *Queries) DeleteUpstream(ctx context.Context, arg DeleteUpstreamParams) error {
	_, err := q.db.Exec(ctx, deleteUpstream, arg.ID, arg.TenantID)
	return err
}

const getUpstream = `-- name: GetUpstream :one
SELECT id, tenant_id, name, url, timeout_ms, enabled, created_at, updated_at FROM upstreams
WHERE id = $1 AND tenant_id = $2
`

type GetUpstreamParams struct {
	ID       uuid.UUID `db:"id" json:"id"`
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
}

func (q *Queries) GetUpstream(ctx context.Context, arg GetUpstreamParams) (Upstream, error) {
	row := q.db.QueryRow(ctx, getUpstream, arg.ID, arg.TenantID)
	var i Upstream
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Url,
		&i.TimeoutMs,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUpstreamsByTenant = `-- name: ListUpstreamsByTenant :many
SELECT id, tenant_id, name, url, timeout_ms, enabled, created_at, updated_at FROM upstreams
WHERE tenant_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListUpstreamsByTenantParams struct {
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
	Limit    int32     `db:"limit" json:"limit"`
	Offset   int32     `db:"offset" json:"offset"`
}

func (q *Queries) ListUpstreamsByTenant(ctx context.Context, arg ListUpstreamsByTenantParams) ([]Upstream, error) {
	rows, err := q.db.Query(ctx, listUpstreamsByTenant, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Upstream
	for rows.Next() {
		var i Upstream
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Url,
			&i.TimeoutMs,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUpstream = `-- name: UpdateUpstream :one
UPDATE upstreams
SET name = $3, url = $4, timeout_ms = $5, enabled = $6
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, name, url, timeout_ms, enabled, created_at, updated_at
`

type UpdateUpstreamParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	TenantID  uuid.UUID `db:"tenant_id" json:"tenant_id"`
	Name      string    `db:"name" json:"name"`
	Url       string    `db:"url" json:"url"`
	TimeoutMs int32     `db:"timeout_ms" json:"timeout_ms"`
	Enabled   bool      `db:"enabled" json:"enabled"`
}

func (q *Queries) UpdateUpstream(ctx context.Context, arg UpdateUpstreamParams) (Upstream, error) {
	row := q.db.QueryRow(ctx, updateUpstream,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.Url,
		arg.TimeoutMs,
		arg.Enabled,
	)
	var i Upstream
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Url,
		&i.TimeoutMs,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
