// Code generated by sqlc. DO NOT EDIT.

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

// ---------- model ----------

type WasmPlugin struct {
	ID         uuid.UUID `db:"id" json:"id"`
	TenantID   uuid.UUID `db:"tenant_id" json:"tenant_id"`
	Name       string    `db:"name" json:"name"`
	Version    string    `db:"version" json:"version"`
	Trigger    string    `db:"trigger" json:"trigger"`
	Sha256     string    `db:"sha256" json:"sha256"`
	StorageURL *string   `db:"storage_url" json:"storage_url,omitempty"`
	// WasmBinary is omitted from JSON responses to keep payloads small.
	WasmBinary []byte    `db:"wasm_binary" json:"-"`
	Config     []byte    `db:"config" json:"config"`
	Enabled    bool      `db:"enabled" json:"enabled"`
	CreatedAt  time.Time `db:"created_at" json:"created_at"`
	UpdatedAt  time.Time `db:"updated_at" json:"updated_at"`
}

// ---------- queries ----------

const createWasmPlugin = `-- name: CreateWasmPlugin :one
INSERT INTO wasm_plugins
    (tenant_id, name, version, trigger, sha256, storage_url, wasm_binary, config, enabled)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, tenant_id, name, version, trigger, sha256, storage_url, wasm_binary, config, enabled, created_at, updated_at`

type CreateWasmPluginParams struct {
	TenantID   uuid.UUID `db:"tenant_id"`
	Name       string    `db:"name"`
	Version    string    `db:"version"`
	Trigger    string    `db:"trigger"`
	Sha256     string    `db:"sha256"`
	StorageURL *string   `db:"storage_url"`
	WasmBinary []byte    `db:"wasm_binary"`
	Config     []byte    `db:"config"`
	Enabled    bool      `db:"enabled"`
}

func (q *Queries) CreateWasmPlugin(ctx context.Context, arg CreateWasmPluginParams) (WasmPlugin, error) {
	row := q.db.QueryRow(ctx, createWasmPlugin,
		arg.TenantID, arg.Name, arg.Version, arg.Trigger, arg.Sha256,
		arg.StorageURL, arg.WasmBinary, arg.Config, arg.Enabled,
	)
	var p WasmPlugin
	err := row.Scan(
		&p.ID, &p.TenantID, &p.Name, &p.Version, &p.Trigger, &p.Sha256,
		&p.StorageURL, &p.WasmBinary, &p.Config, &p.Enabled,
		&p.CreatedAt, &p.UpdatedAt,
	)
	return p, err
}

const listWasmPlugins = `-- name: ListWasmPlugins :many
SELECT id, tenant_id, name, version, trigger, sha256, storage_url, wasm_binary, config, enabled, created_at, updated_at
FROM wasm_plugins
WHERE tenant_id = $1
ORDER BY name, version
LIMIT $2 OFFSET $3`

type ListWasmPluginsParams struct {
	TenantID uuid.UUID `db:"tenant_id"`
	Limit    int32     `db:"limit"`
	Offset   int32     `db:"offset"`
}

func (q *Queries) ListWasmPlugins(ctx context.Context, arg ListWasmPluginsParams) ([]WasmPlugin, error) {
	rows, err := q.db.Query(ctx, listWasmPlugins, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WasmPlugin
	for rows.Next() {
		var p WasmPlugin
		if err := rows.Scan(
			&p.ID, &p.TenantID, &p.Name, &p.Version, &p.Trigger, &p.Sha256,
			&p.StorageURL, &p.WasmBinary, &p.Config, &p.Enabled,
			&p.CreatedAt, &p.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, p)
	}
	return items, rows.Err()
}

const getWasmPlugin = `-- name: GetWasmPlugin :one
SELECT id, tenant_id, name, version, trigger, sha256, storage_url, wasm_binary, config, enabled, created_at, updated_at
FROM wasm_plugins
WHERE id = $1 AND tenant_id = $2`

type GetWasmPluginParams struct {
	ID       uuid.UUID `db:"id"`
	TenantID uuid.UUID `db:"tenant_id"`
}

func (q *Queries) GetWasmPlugin(ctx context.Context, arg GetWasmPluginParams) (WasmPlugin, error) {
	row := q.db.QueryRow(ctx, getWasmPlugin, arg.ID, arg.TenantID)
	var p WasmPlugin
	err := row.Scan(
		&p.ID, &p.TenantID, &p.Name, &p.Version, &p.Trigger, &p.Sha256,
		&p.StorageURL, &p.WasmBinary, &p.Config, &p.Enabled,
		&p.CreatedAt, &p.UpdatedAt,
	)
	return p, err
}

const updateWasmPlugin = `-- name: UpdateWasmPlugin :one
UPDATE wasm_plugins
SET name = $3, version = $4, trigger = $5, sha256 = $6,
    storage_url = $7, wasm_binary = $8, config = $9, enabled = $10,
    updated_at = NOW()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, name, version, trigger, sha256, storage_url, wasm_binary, config, enabled, created_at, updated_at`

type UpdateWasmPluginParams struct {
	ID         uuid.UUID `db:"id"`
	TenantID   uuid.UUID `db:"tenant_id"`
	Name       string    `db:"name"`
	Version    string    `db:"version"`
	Trigger    string    `db:"trigger"`
	Sha256     string    `db:"sha256"`
	StorageURL *string   `db:"storage_url"`
	WasmBinary []byte    `db:"wasm_binary"`
	Config     []byte    `db:"config"`
	Enabled    bool      `db:"enabled"`
}

func (q *Queries) UpdateWasmPlugin(ctx context.Context, arg UpdateWasmPluginParams) (WasmPlugin, error) {
	row := q.db.QueryRow(ctx, updateWasmPlugin,
		arg.ID, arg.TenantID, arg.Name, arg.Version, arg.Trigger, arg.Sha256,
		arg.StorageURL, arg.WasmBinary, arg.Config, arg.Enabled,
	)
	var p WasmPlugin
	err := row.Scan(
		&p.ID, &p.TenantID, &p.Name, &p.Version, &p.Trigger, &p.Sha256,
		&p.StorageURL, &p.WasmBinary, &p.Config, &p.Enabled,
		&p.CreatedAt, &p.UpdatedAt,
	)
	return p, err
}

const deleteWasmPlugin = `-- name: DeleteWasmPlugin :exec
DELETE FROM wasm_plugins WHERE id = $1 AND tenant_id = $2`

type DeleteWasmPluginParams struct {
	ID       uuid.UUID `db:"id"`
	TenantID uuid.UUID `db:"tenant_id"`
}

func (q *Queries) DeleteWasmPlugin(ctx context.Context, arg DeleteWasmPluginParams) error {
	_, err := q.db.Exec(ctx, deleteWasmPlugin, arg.ID, arg.TenantID)
	return err
}
