// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbox.sql

package sqlcgen

import (
	"context"
)

const fetchPendingEvents = `-- name: FetchPendingEvents :many
SELECT id, tenant_id, kafka_topic, payload, created_at, sent_at, kafka_partition, kafka_offset FROM event_outbox
WHERE sent_at IS NULL
ORDER BY id
LIMIT $1
FOR UPDATE SKIP LOCKED
`

// Grabs up to $1 unsent rows in insertion order.
// SKIP LOCKED lets concurrent worker replicas coexist safely.
func (q *Queries) FetchPendingEvents(ctx context.Context, limit int32) ([]EventOutbox, error) {
	rows, err := q.db.Query(ctx, fetchPendingEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventOutbox
	for rows.Next() {
		var i EventOutbox
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.KafkaTopic,
			&i.Payload,
			&i.CreatedAt,
			&i.SentAt,
			&i.KafkaPartition,
			&i.KafkaOffset,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEventSent = `-- name: MarkEventSent :exec
UPDATE event_outbox
SET sent_at         = now(),
    kafka_partition = $2,
    kafka_offset    = $3
WHERE id = $1
`

type MarkEventSentParams struct {
	ID             int64  `db:"id" json:"id"`
	KafkaPartition *int32 `db:"kafka_partition" json:"kafka_partition"`
	KafkaOffset    *int64 `db:"kafka_offset" json:"kafka_offset"`
}

func (q *Queries) MarkEventSent(ctx context.Context, arg MarkEventSentParams) error {
	_, err := q.db.Exec(ctx, markEventSent, arg.ID, arg.KafkaPartition, arg.KafkaOffset)
	return err
}
